name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install apt test dependencies
      run: |
        sudo apt update
        sudo apt install -y libsmbclient-dev samba
    - name: Install go dependencies
      run: |
        go get -t -v ./...
    - name: Test
      run: |
        go test ./...
